image:
  repository: codeberg.org/forgejo/forgejo
  tag: 1.18.5-0-rootless1.18.5@sha256:e94cc333f336a7bdbc02d10575f7d92b10440c682dc846e6c544d779b8ea0656
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

service:
  main:
    ports:
      main:
        port: 10037
        targetPort: 3000
  ssh:
    enabled: true
    ports:
      ssh:
        enabled: true
        port: 2222
        targetPort: 2222

envFrom:
  - configMapRef:
      name: gitea-env

initContainers:
  1-init-directories:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: ["/usr/sbin/init_directory_structure.sh"]
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
    envFrom:
      - configMapRef:
          name: gitea-env
    volumeMounts:
      - name: init
        mountPath: "/usr/sbin"
      - name: temp
        mountPath: "/tmp"
      - name: config
        mountPath: "/etc/gitea/conf"
      - name: data
        mountPath: "/data"
  2-configure-gitea:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: ["/usr/sbin/configure_gitea.sh"]
    envFrom:
      - configMapRef:
          name: gitea-env
    volumeMounts:
      - name: init
        mountPath: "/usr/sbin"
      - name: temp
        mountPath: "/tmp"
      - name: data
        mountPath: "/data"

persistence:
  data:
    enabled: true
    mountPath: "/data"
  temp:
    enabled: true
    mountPath: "/tmp"
    type: emptyDir
  varlib:
    enabled: true
    mountPath: "/var/lib/gitea"
    type: emptyDir

# Configure commit/action signing prerequisites
signing:
  enabled: true
  gpgHome: /data/git/.gnupg

admin:
  username: giteaadmin
  password: r8sA8CPHD9!bt6d
  email: "gitea@local.domain"

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    #  additionalLabels:
    #    prometheus-release: prom1

ldap:
  enabled: false
  # name:
  # securityProtocol:
  # host:
  # port:
  # userSearchBase:
  # userFilter:
  # adminFilter:
  # emailAttribute:
  # bindDn:
  # bindPassword:
  # usernameAttribute:
  # sshPublicKeyAttribute:

oauth:
  enabled: false
  # name:
  # provider:
  # key:
  # secret:
  # autoDiscoverUrl:
  # useCustomUrls:
  # customAuthUrl:
  # customTokenUrl:
  # customProfileUrl:
  # customEmailUrl:

config:
  APP_NAME: "Forgejo: Beyond coding. We forge."
  RUN_MODE: dev
  ALLOWED_HOST_LIST: "127.0.0.1"
  nodeIP: 127.0.0.1

customConfig:
  []
  # - name: test
  #   keys:
  #     - name: testkey
  #       value: testvalue

# Enabled postgres
postgresql:
  enabled: false
  existingSecret: "dbcreds"
  postgresqlUsername: gitea
  postgresqlDatabase: gitea

# --  memcached dependency settings
memcached:
  enabled: true

portal:
  enabled: true
